default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^.*\.md$
      - id: end-of-file-fixer
      - id: debug-statements
      - id: no-commit-to-branch
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: detect-private-key
      - id: check-merge-conflict

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint

  - repo: https://github.com/timothycrosley/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [ "--profile", "black" ]
        # extra dependencies for config in pyproject.toml
        additional_dependencies: ["toml"]

  - repo: https://github.com/ambv/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.4
    hooks:
      - id: pylint
        exclude: ^(docs/).*$
        args: ["--disable=import-error,no-name-in-module"]

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle

  - repo: https://github.com/codingjoe/relint
    rev: 3.3.1
    hooks:
      - id: relint
